### ISSUE TITLE
Running OWA on a subdomain

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/owa-php-sdk#4]
**Description**  
Hey Peter, is it possible to run owa on an subdomain instead of running it on the same domain?
Is the PHP SDK ready to already?

**Comment by padams** [comment]
Not sure how i missed this but yes you can run OWA on whatever domain you want as long as you are careful about cookies. 

I'm packaging up the SDK now so we will have a v1.0 hopefully this week.
