### ISSUE TITLE
can't have semi colon in cookie path

### ISSUE THREAD

**Issue by daemon-byte** [Open-Web-Analytics/owa-php-sdk#8]
https://github.com/Open-Web-Analytics/owa-php-sdk/blob/master/src/Tracker/State.php#L371

On line 371 you added the line "$path .= '; SameSite=lax';". This is causing php to reject it claiming you can't have a semi colon in the cookie path. Is this something you are experiencing as well?

**Comment by almare** [comment]
Same here
